"""add services, updated appointment, persona, forms

Revision ID: 3891f62d8810
Revises: 8bb9e943352d
Create Date: 2026-10-04 22:05:47.483700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3891f62d8810'
down_revision: Union[str, Sequence[str], None] = '8bb9e943352d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- manually added: create enum types before use ---
    persona_relation = sa.Enum(
        'self_', 'child', 'spouse', 'parent', 'sibling', 'other',
        name='personarelation',
    )
    contact_mode = sa.Enum(
        'phone', 'email', 'messenger', 'instagram',
        name='contactmode',
    )
    persona_relation.create(op.get_bind(), checkfirst=True)
    contact_mode.create(op.get_bind(), checkfirst=True)
    # --- end manual addition ---

    op.create_table('services',
                    sa.Column('service_id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('service_id')
                    )
    op.add_column('appointments', sa.Column(
        'service_id', sa.Uuid(), nullable=False))
    op.add_column('appointments', sa.Column('presenting_concern',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'services', [
                          'service_id'], ['service_id'])
    op.add_column('forms', sa.Column('consent_version',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('forms', sa.Column('terms_signer_name',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('forms', sa.Column('terms_signer_relation',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('forms', sa.Column(
        'scope_acknowledged', sa.Boolean(), nullable=False))
    op.add_column('forms', sa.Column(
        'is_overseas_or_foreign', sa.Boolean(), nullable=False))
    op.add_column('forms', sa.Column(
        'overseas_acknowledged', sa.Boolean(), nullable=False))
    op.add_column('forms', sa.Column(
        'information_confirmed', sa.Boolean(), nullable=False))
    op.add_column('forms', sa.Column('consent_signer_name',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('forms', sa.Column(
        'signed_at', sa.DateTime(), nullable=False))
    op.add_column('persona', sa.Column(
        'relation_to_account_holder', persona_relation, nullable=False))
    op.add_column('persona', sa.Column('persona_name',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('persona', sa.Column(
        'date_of_birth', sa.Date(), nullable=False))
    op.add_column('persona', sa.Column(
        'occupation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('persona', sa.Column(
        'nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('persona', sa.Column('permanent_address',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('persona', sa.Column('present_address',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('persona', sa.Column('contact_number',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('persona', sa.Column('socmed_platform',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('persona', sa.Column('socmed_username',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('persona', sa.Column(
        'preferred_contact_mode', contact_mode, nullable=False))
    op.add_column('persona', sa.Column('emergency_contact_name',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('persona', sa.Column('emergency_contact_relation',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('persona', sa.Column('emergency_contact_number',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('persona', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('full_name', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.drop_column('persona', 'emergency_contact_number')
    op.drop_column('persona', 'emergency_contact_relation')
    op.drop_column('persona', 'emergency_contact_name')
    op.drop_column('persona', 'preferred_contact_mode')
    op.drop_column('persona', 'socmed_username')
    op.drop_column('persona', 'socmed_platform')
    op.drop_column('persona', 'contact_number')
    op.drop_column('persona', 'present_address')
    op.drop_column('persona', 'permanent_address')
    op.drop_column('persona', 'nationality')
    op.drop_column('persona', 'occupation')
    op.drop_column('persona', 'date_of_birth')
    op.drop_column('persona', 'persona_name')
    op.drop_column('persona', 'relation_to_account_holder')
    op.drop_column('forms', 'signed_at')
    op.drop_column('forms', 'consent_signer_name')
    op.drop_column('forms', 'information_confirmed')
    op.drop_column('forms', 'overseas_acknowledged')
    op.drop_column('forms', 'is_overseas_or_foreign')
    op.drop_column('forms', 'scope_acknowledged')
    op.drop_column('forms', 'terms_signer_relation')
    op.drop_column('forms', 'terms_signer_name')
    op.drop_column('forms', 'consent_version')
    op.drop_constraint('fk_appointments_service_id_services',
                       'appointments', type_='foreignkey')
    op.drop_column('appointments', 'presenting_concern')
    op.drop_column('appointments', 'service_id')
    op.drop_table('services')

    # --- manually added: drop enum types after columns that use them ---
    sa.Enum(name='personarelation').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='contactmode').drop(op.get_bind(), checkfirst=True)
    # --- end manual addition ---
    # ### end Alembic commands ###
